export type EmojiList = {
  data: Data;
  [property: string]: any
}

type Data = {
  visionBaseEmoticons: VisionBaseEmoticons;
  [property: string]: any
}

type VisionBaseEmoticons = {
  __typename: string
  iconUrls: IconUrls;
  [property: string]: any
}

type IconUrls = {
  '[666]': string
  '[addition]': string
  '[ahead]': string
  '[airdrop]': string
  '[almostcry]': string
  '[alpaca]': string
  '[amazing]': string
  '[angry]': string
  '[arranged]': string
  '[awkard]': string
  '[awkward]': string
  '[balloon]': string
  '[banger]': string
  '[blissful]': string
  '[boom]': string
  '[boss]': string
  '[brick]': string
  '[bro]': string
  '[BusyCrazy]': string
  '[bye]': string
  '[cake]': string
  '[camera]': string
  '[CanNotFinish]': string
  '[cat]': string
  '[celebrate]': string
  '[celebrity]': string
  '[checkmark]': string
  '[cheers]': string
  '[clap]': string
  '[ComeOn]': string
  '[Confused]': string
  '[cool]': string
  '[crazy]': string
  '[cross]': string
  '[crown]': string
  '[cry]': string
  '[cryLaugh]': string
  '[Cuddle]': string
  '[curious]': string
  '[curl]': string
  '[curse]': string
  '[dance]': string
  '[daydream]': string
  '[daydreaming]': string
  '[dazzling]': string
  '[despise]': string
  '[devastated]': string
  '[dial]': string
  '[dignose]': string
  '[dirtytalk]': string
  '[disdain]': string
  '[distressed]': string
  '[dizzy]': string
  '[dog]': string
  '[dogfood]': string
  '[double]': string
  '[dragon]': string
  '[eat]': string
  '[eatmelon]': string
  '[emo]': string
  '[energetic]': string
  '[exercise]': string
  '[explosion]': string
  '[eyeroll]': string
  '[EyesRolling]': string
  '[facepalm]': string
  '[fade]': string
  '[fighting]': string
  '[fire]': string
  '[fireworks]': string
  '[fistBump]': string
  '[flirting]': string
  '[follow]': string
  '[forcesmile]': string
  '[fortune]': string
  '[fossil]': string
  '[frown]': string
  '[furious]': string
  '[gamepad]': string
  '[GameTime]': string
  '[get]': string
  '[ghost]': string
  '[gold]': string
  '[good]': string
  '[goodmorning]': string
  '[goodnight]': string
  '[grin]': string
  '[handheart]': string
  '[hanging]': string
  '[happy]': string
  '[HappyNewYear]': string
  '[HappySpringFestival]': string
  '[hard]': string
  '[HaveFun]': string
  '[heart]': string
  '[helmet]': string
  '[Hi]': string
  '[hitface]': string
  '[hole]': string
  '[Homework]': string
  '[hug]': string
  '[hustle]': string
  '[ILoveU]': string
  '[immediately]': string
  '[joyful]': string
  '[kiss]': string
  '[kitty]': string
  '[knee]': string
  '[knife]': string
  '[lateNight]': string
  '[latern]': string
  '[laughcry]': string
  '[learning]': string
  '[left]': string
  '[leftfist]': string
  '[like]': string
  '[lion]': string
  '[lipstick]': string
  '[love]': string
  '[loveu]': string
  '[luck]': string
  '[makeup]': string
  '[microphone]': string
  '[minus]': string
  '[mirror]': string
  '[mojito]': string
  '[money]': string
  '[mouse]': string
  '[muscle]': string
  '[music]': string
  '[N95]': string
  '[nail]': string
  '[naughty]': string
  '[nice]': string
  '[no]': string
  '[nolisten]': string
  '[nolook]': string
  '[nosebleed]': string
  '[nospeak]': string
  '[nostrils]': string
  '[oh]': string
  '[ok]': string
  '[omg]': string
  '[oops]': string
  '[overworking]': string
  '[pan]': string
  '[party]': string
  '[pat]': string
  '[pig]': string
  '[pigfoot]': string
  '[pignose]': string
  '[plea]': string
  '[please]': string
  '[pollution]': string
  '[poor]': string
  '[pout]': string
  '[pray]': string
  '[prickekheart]': string
  '[Progress0]': string
  '[Progress50]': string
  '[Progress99]': string
  '[quiet]': string
  '[rainbow]': string
  '[Really]': string
  '[received]': string
  '[redface]': string
  '[redpacket]': string
  '[relax]': string
  '[rich]': string
  '[right]': string
  '[rightFist]': string
  '[rose]': string
  '[rotate]': string
  '[sad]': string
  '[salute]': string
  '[SayHi]': string
  '[scare]': string
  '[scared]': string
  '[seen]': string
  '[shakeHands]': string
  '[shiba]': string
  '[shit]': string
  '[shutup]': string
  '[shy]': string
  '[simper]': string
  '[skeleton]': string
  '[slacking]': string
  '[sleep]': string
  '[sleepy]': string
  '[smile]': string
  '[sneak]': string
  '[snicker]': string
  '[snort]': string
  '[sophisticated]': string
  '[Sorry]': string
  '[sour]': string
  '[stable]': string
  '[starryeyed]': string
  '[StayingUpLate]': string
  '[StayPositive]': string
  '[stunned]': string
  '[stupid]': string
  '[surprised]': string
  '[sweat]': string
  '[sweaty]': string
  '[tears]': string
  '[tease]': string
  '[TellMeMore]': string
  '[thanks]': string
  '[think]': string
  '[titter]': string
  '[touch]': string
  '[treacherous]': string
  '[VacationTime]': string
  '[vanillcake]': string
  '[vibrant]': string
  '[vomit]': string
  '[vomitblood]': string
  '[Wait]': string
  '[waiting]': string
  '[wanttoeat]': string
  '[washhands]': string
  '[watergun]': string
  '[weary]': string
  '[welcome]': string
  '[wetwipes]': string
  '[what]': string
  '[whistle]': string
  '[win]': string
  '[wipenose]': string
  '[won]': string
  '[wronged]': string
  '[yawn]': string
  '[yes]': string
  '[YouRight]': string
  '[一起嗨皮]': string
  '[上号]': string
  '[上吊]': string
  '[上號]': string
  '[不听]': string
  '[不看]': string
  '[不聽]': string
  '[不說]': string
  '[不说]': string
  '[乾杯]': string
  '[亲亲]': string
  '[优秀]': string
  '[你好呀]': string
  '[做不完]': string
  '[做作业]': string
  '[做作業]': string
  '[健身]': string
  '[偷瞄]': string
  '[偷笑]': string
  '[優秀]': string
  '[元宝]': string
  '[元寶]': string
  '[元旦快乐]': string
  '[元旦快樂]': string
  '[元气满满]': string
  '[元氣滿滿]': string
  '[充满干劲]': string
  '[充滿幹勁]': string
  '[先睡了]': string
  '[八倍鏡]': string
  '[八倍镜]': string
  '[再見]': string
  '[再见]': string
  '[冷汗]': string
  '[减1]': string
  '[出去丸]': string
  '[出去玩]': string
  '[出魂儿]': string
  '[出魂兒]': string
  '[加1]': string
  '[加油]': string
  '[勤洗手]': string
  '[化妆]': string
  '[化妝]': string
  '[南]': string
  '[卷]': string
  '[叉号]': string
  '[叉號]': string
  '[双鸡]': string
  '[发]': string
  '[发呆]': string
  '[口紅]': string
  '[口红]': string
  '[可怜]': string
  '[可憐]': string
  '[右哼哼]': string
  '[右拳]': string
  '[吃瓜]': string
  '[吃飯]': string
  '[吃饭]': string
  '[吐彩虹]': string
  '[吐血]': string
  '[吓]': string
  '[听音乐]': string
  '[吹口哨]': string
  '[呆住]': string
  '[呕吐]': string
  '[哈欠]': string
  '[哦]': string
  '[哭笑]': string
  '[哼]': string
  '[嘔吐]': string
  '[嘘]': string
  '[嘣]': string
  '[嚇]': string
  '[囧]': string
  '[困]': string
  '[困死了]': string
  '[坏笑]': string
  '[坑]': string
  '[塗指甲]': string
  '[壞笑]': string
  '[大便]': string
  '[大哥]': string
  '[大哭]': string
  '[大鼻孔]': string
  '[天啊]': string
  '[头盔]': string
  '[奸笑]': string
  '[好运来]': string
  '[好運來]': string
  '[委屈]': string
  '[学习]': string
  '[學習]': string
  '[安排]': string
  '[对不起]': string
  '[对号]': string
  '[尊嘟假嘟]': string
  '[對不起]': string
  '[對號]': string
  '[尴尬]': string
  '[尷尬]': string
  '[左哼哼]': string
  '[左拳]': string
  '[已閱]': string
  '[已阅]': string
  '[干杯]': string
  '[平底鍋]': string
  '[平底锅]': string
  '[庆祝]': string
  '[強顏歡笑]': string
  '[强颜欢笑]': string
  '[微笑]': string
  '[心心]': string
  '[必勝]': string
  '[必胜]': string
  '[忙疯了]': string
  '[忙瘋了]': string
  '[快哭了]': string
  '[怒言]': string
  '[思考]': string
  '[惊恐]': string
  '[惊讶]': string
  '[想吃]': string
  '[愉快]': string
  '[愛你]': string
  '[愛心]': string
  '[慶祝]': string
  '[憨笑]': string
  '[我愛你]': string
  '[我爱你]': string
  '[我看行]': string
  '[戴口罩]': string
  '[手柄]': string
  '[扎心]': string
  '[打call]': string
  '[打招呼]': string
  '[打电话]': string
  '[打脸]': string
  '[打臉]': string
  '[打電話]': string
  '[抓狂]': string
  '[抠鼻]': string
  '[抱抱]': string
  '[抱拳]': string
  '[拍一拍]': string
  '[拜托]': string
  '[拜託]': string
  '[挑逗]': string
  '[捂脸]': string
  '[捂臉]': string
  '[握手]': string
  '[摄像机]': string
  '[摳鼻]': string
  '[摸头]': string
  '[摸頭]': string
  '[摸魚]': string
  '[摸鱼]': string
  '[撇嘴]': string
  '[擦鼻涕]': string
  '[攝像機]': string
  '[收到]': string
  '[放假啦]': string
  '[放輕鬆]': string
  '[放轻松]': string
  '[敬礼]': string
  '[敬禮]': string
  '[新年快乐]': string
  '[新年快樂]': string
  '[旋轉]': string
  '[旋转]': string
  '[早上好]': string
  '[星星眼]': string
  '[晕]': string
  '[暈]': string
  '[暴汗]': string
  '[有八卦]': string
  '[期待]': string
  '[板砖]': string
  '[板磚]': string
  '[柴犬]': string
  '[欢迎]': string
  '[歡迎]': string
  '[正能量]': string
  '[比心]': string
  '[气球]': string
  '[氣球]': string
  '[水枪]': string
  '[水槍]': string
  '[求求了]': string
  '[汗]': string
  '[流鼻血]': string
  '[涂指甲]': string
  '[減1]': string
  '[湿巾]': string
  '[濕巾]': string
  '[火]': string
  '[灯笼]': string
  '[点点关注]': string
  '[点赞]': string
  '[烟花]': string
  '[煙花]': string
  '[熬夜]': string
  '[熬夜工作]': string
  '[燈籠]': string
  '[爆炸]': string
  '[爱你]': string
  '[爱心]': string
  '[狗]': string
  '[狗粮]': string
  '[狗糧]': string
  '[狮子]': string
  '[猪头]': string
  '[猪蹄]': string
  '[猪鼻子]': string
  '[猫]': string
  '[獅子]': string
  '[玫瑰]': string
  '[生气]': string
  '[生氣]': string
  '[略略略]': string
  '[疑問]': string
  '[疑问]': string
  '[疯狂工作]': string
  '[疲惫]': string
  '[疲憊]': string
  '[瘋狂工作]': string
  '[發]': string
  '[發呆]': string
  '[白眼]': string
  '[皇冠]': string
  '[皱眉]': string
  '[皺眉]': string
  '[睡覺]': string
  '[睡觉]': string
  '[石化]': string
  '[礼花]': string
  '[祈祷]': string
  '[祈禱]': string
  '[福字]': string
  '[禮花]': string
  '[稍等]': string
  '[稳]': string
  '[穩]': string
  '[空投]': string
  '[笑哭]': string
  '[紅包]': string
  '[紅臉蛋]': string
  '[絕]': string
  '[網紅]': string
  '[網紅貓]': string
  '[红包]': string
  '[红脸蛋]': string
  '[绝]': string
  '[网红]': string
  '[网红猫]': string
  '[罵你]': string
  '[羊駝]': string
  '[羊驼]': string
  '[美滋滋]': string
  '[羞涩]': string
  '[羞澀]': string
  '[翻白眼]': string
  '[老司机]': string
  '[老司機]': string
  '[老鐵]': string
  '[老铁]': string
  '[老鼠]': string
  '[聽音樂]': string
  '[肌肉]': string
  '[胡思乱想]': string
  '[胡思亂想]': string
  '[色]': string
  '[花謝了]': string
  '[花谢了]': string
  '[莫吉托]': string
  '[菜刀]': string
  '[落泪]': string
  '[落淚]': string
  '[蛋糕]': string
  '[裂开]': string
  '[裂開]': string
  '[装傻]': string
  '[裝傻]': string
  '[親親]': string
  '[調皮]': string
  '[讓人頭大]': string
  '[讚]': string
  '[让人头大]': string
  '[调皮]': string
  '[豬蹄]': string
  '[豬頭]': string
  '[豬鼻子]': string
  '[貓]': string
  '[貼貼]': string
  '[贏麻了]': string
  '[贴贴]': string
  '[赞]': string
  '[赢麻了]': string
  '[跪下]': string
  '[跳舞]': string
  '[辣眼睛]': string
  '[进度0]': string
  '[进度50]': string
  '[进度99]': string
  '[進度0]': string
  '[進度50]': string
  '[進度99]': string
  '[遙遙領先]': string
  '[遥遥领先]': string
  '[鄙視]': string
  '[鄙视]': string
  '[酷]': string
  '[酸了]': string
  '[錢]': string
  '[钱]': string
  '[閉嘴]': string
  '[闭嘴]': string
  '[难受]': string
  '[难过]': string
  '[难过至极]': string
  '[雙雞]': string
  '[難受]': string
  '[難過]': string
  '[難過至極]': string
  '[雾霾]': string
  '[霧霾]': string
  '[鞭炮]': string
  '[頭盔]': string
  '[香子蘭蛋糕]': string
  '[香草蛋糕]': string
  '[馬上安排]': string
  '[驚恐]': string
  '[驚訝]': string
  '[马上安排]': string
  '[骂你]': string
  '[骷髅]': string
  '[骷髏]': string
  '[麥克風]': string
  '[麦克风]': string
  '[黑脸问]': string
  '[黑臉問]': string
  '[點贊]': string
  '[點點關注]': string
  '[鼓掌]': string
  '[齜牙]': string
  '[龇牙]': string
  '[龍]': string
  '[龙]': string;
  [property: string]: any
}
