import { rm } from 'node:fs/promises'

import { generateFiles } from 'fumadocs-openapi'

import { openapi } from '../lib/openapi'

/**
 * 从 `packages/core/openapi.json` 生成 59 个端点参考页。
 *
 * 产物**不进 git**（`.gitignore` 忽略整个 `api/http/`），由 `docs:api` 在
 * `next build` / `next dev` / `typecheck` 之前跑。手写一份路由表正是阶段 8 要根治的事。
 *
 * 三个不得不自己处理的点：
 * - **先删再生成**：上游只做 mkdir + writeFile，从不清理。端点改名或下线后，
 *   旧页会永久留在 content 里被 `getPages()` 继续吐出来（幽灵端点）。
 * - **落到 `api/http/` 而不是 `api/`**：fumadocs 解析 meta 的 `pages` 条目时
 *   文件夹优先于同名文件，生成 `api/bilibili/` 会让手写的 `api/bilibili.mdx`
 *   静默变成孤儿页（URL 还在、侧边栏没了）；而 `meta: true` 写的根 meta.json
 *   会原地覆盖已提交的 `api/meta.json`。
 * - **`name()` 削掉 operationId 的平台前缀**：规范里 operationId 必须全局唯一
 *   （`emojiList` 四个平台各有一条），所以是 `bilibili_videoInfo`；而文件已经
 *   在 `bilibili/` 目录下，页面名只要 `videoInfo`。
 */
const OUT = './content/docs/v7/usage/api/http'
const URL_BASE = '/docs/v7/usage/api/http'

interface OutputFile {
  path: string
  content: string
}

const frontmatterTitle = (content: string): string => /^title:\s*(.+)$/m.exec(content)?.[1]?.trim() ?? ''

/**
 * 索引页（`api/http/index.mdx`）。
 *
 * 自己拼而不用上游的 `index` 选项：`groupBy: 'tag'` 下顶层条目全是 group，
 * 生成器会把它们跳过，产出的是一个空 `<Cards>`。
 *
 * 这一页同时承担一件必须说清的事：playground **直连你本机的 amagi 服务**，
 * 文档站没有挂公共代理（代理会转发收到的全部 header 与 body，含 HttpOnly
 * `Cookie` 与 `Authorization`，而 amagi 服务端握着运营者的四平台 cookie 与 token）。
 * @param files - 本次生成的全部文件（页面 + 各级 meta.json）
 * @returns index.mdx 的内容
 */
const indexPage = (files: OutputFile[]): string => {
  // 生成器给的 path 是平台分隔符（Windows 上是反斜杠），统一成 /
  const entries = files.map((file) => ({ path: file.path.split('\\').join('/'), content: file.content }))
  const rootMeta = entries.find((file) => file.path === 'meta.json')
  const platforms = rootMeta ? ((JSON.parse(rootMeta.content) as { pages?: string[] }).pages ?? []) : []

  const sections = platforms.map((platform) => {
    const metaFile = entries.find((file) => file.path === `${platform}/meta.json`)
    const label = metaFile ? (JSON.parse(metaFile.content) as { title?: string }).title : undefined
    const pages = entries
      .filter((file) => file.path.startsWith(`${platform}/`) && file.path.endsWith('.mdx'))
      .map((file) => ({ slug: file.path.slice(platform.length + 1, -'.mdx'.length), title: frontmatterTitle(file.content) }))
      .sort((a, b) => a.slug.localeCompare(b.slug))

    const cards = pages.map((page) => `  <Card title="${page.title}" href="${URL_BASE}/${platform}/${page.slug}" />`).join('\n')
    return `## ${label ?? platform}（${pages.length}）\n\n<Cards>\n${cards}\n</Cards>`
  })

  const total = entries.filter((file) => file.path.endsWith('.mdx') && file.path.includes('/')).length

  return `---
title: HTTP 端点参考
description: ${total} 个 HTTP 端点，由端点注册表派生的 OpenAPI 规范生成
---

{/* This file was generated by scripts/generate-docs.ts. Do not edit it directly. */}

四个平台共 ${total} 个 HTTP 端点。本节每一页都由 \`packages/core/openapi.json\` 生成，
而那份规范又由四个端点注册表派生（\`packages/core/scripts/gen-openapi.mts\`）——
所以这里的路径、参数与响应形状不可能与代码脱节。

SDK 侧的方法参考在[各平台 API 页](/docs/v7/usage/api/douyin)，两者是同一批端点的两种形态。

<Callout type="warn">
  每页的 playground **直连你本机启动的 amagi 服务**（默认 \`http://127.0.0.1:4567\`），
  需要先自行把服务跑起来 —— 文档站没有挂公共代理，因为代理会转发收到的全部 header 与
  body（含 HttpOnly \`Cookie\` 与 \`Authorization\`），而 amagi 服务端握着运营者的四平台
  cookie 与可选 token。浏览器可能因跨域（CORS）拦下请求，这是预期行为。
</Callout>

${sections.join('\n\n')}
`
}

await rm(OUT, { recursive: true, force: true })

await generateFiles({
  input: openapi,
  output: OUT,
  per: 'operation',
  groupBy: 'tag',
  // 只在 OUT 内部写 meta.json，不碰手写的 api/meta.json
  meta: true,
  // 取默认 false：开了 description 就只进正文、不进 frontmatter，
  // 而本仓的 DocsDescription / og 图 / MCP 列表都读 page.data.description
  includeDescription: false,
  addGeneratedComment: true,
  name (output) {
    if (output.type !== 'operation') return 'index'
    const operation = this.document.paths?.[output.item.path]?.[output.item.method]
    const operationId = (operation as { operationId?: string } | undefined)?.operationId
    return operationId ? operationId.replace(/^[^_]+_/, '') : 'index'
  },
  beforeWrite (files) {
    // 根 meta.json 由生成器写出且没有 title（parent 为 undefined），
    // 侧边栏会显示目录名 "Http"。在写盘前补上中文标题与图标
    const root = files.find((file) => file.path === 'meta.json')
    if (root) {
      root.content = `${JSON.stringify({ title: 'HTTP 端点参考', icon: 'Server', ...(JSON.parse(root.content) as object) }, null, 2)}\n`
    }
    files.push({ path: 'index.mdx', content: indexPage(files) })
  }
})
