#!/usr/bin/env sh
. "$(dirname -- "$0")/_/h"

if git diff --cached --name-only --diff-filter=ACMRD | grep -q .; then
  echo "🧩 检测到暂存改动，更新 core 的 timestamp 字段..."
  node --import tsx .husky/husky-tasks.ts
  git add packages/core/package.json
fi
