name: Manual Deploy

on:
  workflow_dispatch:  # 只允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest  # 指定运行环境

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # 指定Node.js版本

      - name: Install dependencies and Build package
        run: |
          npm install
          npm run build
          rm -rf lib/dev.js lib/dev.d.ts

      - name: Install Git
        run: |
          sudo apt update
          sudo apt install -y git

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_TOKEN }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global url."git@github.com:".insteadOf "https://github.com/"

      - name: Clone SSH repository
        run: |
          git clone git@github.com:${{secrets.GIT_USERNAME}}/${{secrets.REPO_NAME}}.git ../${{secrets.REPO_NAME}}

      - name: Move lib directory
        run: cp -r lib ../${{secrets.REPO_NAME}}/amagi/

      - name: Set Git config
        run: |
          cd ../${{secrets.REPO_NAME}}
          git config user.name "${{secrets.GIT_USERNAME}}"
          git config user.email "${{secrets.GIT_USER_EMAIL}}"

      - name: Add, Commit, and Push changes
        run: |
          cd ../${{secrets.REPO_NAME}}
          git add amagi/lib
          git commit -m "跟进上游" --allow-empty
          git push